menu:
    # Blog: /
    Archive: /archives
      #iGitHub: /
      #Stackoverflow: /
    About: /about
    Link: /favorites
    Rss: /atom.xml
    Favorites: https://web.lain.buzz

favicon: /favicon.png
logo: /logo.ico

# Comment
# e.g disqus: helloworld
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017

# Styles shoule be found in the list: https://highlightjs.org/static/demo/
# use the lowercase letters and replace space with -
codestyle: solarized-light
