# Header
nav:
  首页: ../../
# Categories: /category
  标签: /tag

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/xiongjum
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: neutral

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# maple
maple:
  enable: true
  count: 10
  speed: 1


